apiVersion: v1
kind: Service
metadata:
  name: employee-backend
spec:
  selector:
    app: employee-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: employee-frontend
spec:
  selector:
    app: employee-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer

